p8105_hw2_zj2357
================
Zekai Jin
2022-10-02

First of all, we should include the libraries we are using and prepare
the dataset.

``` r
library(tidyverse)
library(readxl)
```

# Problem 1

``` r
nyc_transit = read_csv(
  "data/NYC_Transit_Subway_Entrance_And_Exit_Data.csv",
  col_types = cols(Route8 = "c", Route9 = "c", Route10 = "c", Route11 = "c")) %>%
  janitor::clean_names() %>%
  select(line,
         station_name,
         station_latitude,
         station_longitude,
         route1:route11,
         entry,
         vending,
         entrance_type,
         ada) %>%
  mutate(entry = ifelse(entry == "YES", TRUE, FALSE))
```

So far, the dataset(1868 rows, 19 columns) contains the information of
all entries/exits from NYC transit, including the station info, the
routes, the vending machine and ADA compliance. I cleaned the data under
the instruction of the problem. However, the data is still not tidy.

First, the datatype of some columns are not correct. For example, the
“vending” and “ada” columns should be logical, and “entrance_type”
variable should be a factor. Meanwhile, the “route” info is not arranged
in a tidy way. Lastly, the information for the station, such as the
position of the station and routes, is mixed with information for
entrances, such as vending machine information. This introduced
redundancy to the data that we don’t need.

Based on the previous analysis, we can further tidy the data, and finish
the problems:

``` r
nyc_transit =
  mutate(nyc_transit,
         vending = ifelse(vending == "YES", TRUE, FALSE),
         entrance_type = factor(entrance_type))
nyc_station = select(nyc_transit,-entry,-vending,-entrance_type) %>%
  unique() %>%
  distinct(line,station_name,.keep_all = TRUE)

nyc_entrance = select(nyc_transit,line,station_name,entry,vending,entrance_type)
```

According to the data, using inline r, there are 465 different stations,
and 84 stations are ada compliant. Meanwhile, 37.7% entrances without
vending allow entrance.

Then, we reformart based on the route variables,

``` r
nyc_station =
  pivot_longer(
    nyc_station,
    route1:route11,
    names_to = "route_number",
    values_to = "route"
  ) %>%
  drop_na(route)
```

Thus, 60 different stations serves the A train. Among these trains, 17
are ada compliant.

# Problem 2

First, clean the data based on the requirements,

``` r
rm(list = ls())
mr_trash_df =
  read_excel(
    "data/Trash Wheel Collection Data.xlsx",
    sheet = "Mr. Trash Wheel",
    range = "A2:N549"
  ) %>%
  janitor::clean_names() %>%
  mutate(
    sports_balls = as.integer(sports_balls),
    year = as.double(year),
    trash_wheel = rep("Mr.",547)
  )

prof_trash_df = 
  read_excel(
    "data/Trash Wheel Collection Data.xlsx",
    sheet = "Professor Trash Wheel",
    range = "A2:M96"
  ) %>%
  janitor::clean_names() %>%
  mutate(
    trash_wheel = rep("Professor", 94)
  )
  
trash_df = full_join(mr_trash_df, prof_trash_df)%>%
  select(trash_wheel, everything())
```

    ## Joining, by = c("dumpster", "month", "year", "date", "weight_tons",
    ## "volume_cubic_yards", "plastic_bottles", "polystyrene", "cigarette_butts",
    ## "glass_bottles", "grocery_bags", "chip_bags", "homes_powered", "trash_wheel")

``` r
trash_df
```

    ## # A tibble: 641 × 15
    ##    trash_wheel dumpster month  year date                weight…¹ volum…² plast…³
    ##    <chr>          <dbl> <chr> <dbl> <dttm>                 <dbl>   <dbl>   <dbl>
    ##  1 Mr.                1 May    2014 2014-05-16 00:00:00     4.31      18    1450
    ##  2 Mr.                2 May    2014 2014-05-16 00:00:00     2.74      13    1120
    ##  3 Mr.                3 May    2014 2014-05-16 00:00:00     3.45      15    2450
    ##  4 Mr.                4 May    2014 2014-05-17 00:00:00     3.1       15    2380
    ##  5 Mr.                5 May    2014 2014-05-17 00:00:00     4.06      18     980
    ##  6 Mr.                6 May    2014 2014-05-20 00:00:00     2.71      13    1430
    ##  7 Mr.                7 May    2014 2014-05-21 00:00:00     1.91       8     910
    ##  8 Mr.                8 May    2014 2014-05-28 00:00:00     3.7       16    3580
    ##  9 Mr.                9 June   2014 2014-06-05 00:00:00     2.52      14    2400
    ## 10 Mr.               10 June   2014 2014-06-11 00:00:00     3.76      18    1340
    ## # … with 631 more rows, 7 more variables: polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, grocery_bags <dbl>,
    ## #   chip_bags <dbl>, sports_balls <int>, homes_powered <dbl>, and abbreviated
    ## #   variable names ¹​weight_tons, ²​volume_cubic_yards, ³​plastic_bottles

The `trash_df` dataframe contains the amount of items collected by
different dumpstersm, categorized by trash wheel types (Mr. or
Professor). There are 641 observations, each contains 15 columns.

For the cleaned data, the total weight collected by Professor Trash
Wheel is 190.12, and the total number of sport balls collected by
Mr. Trash Wheel is 6869

# Problem 3

``` r
rm(list = ls())

pol_df = 
  read_csv("data/fivethirtyeight_datasets/pols-month.csv") %>%
  separate(
    mon,
    into = c("year","month","day"),
    sep =  "-"
  ) %>%
  mutate(
    president = ifelse(prez_dem == 1, "dem", "gop"),
    year = as.double(year),
    month = month.abb[as.integer(month)]
  ) %>%
  select(-prez_dem, -prez_gop, -day)

snp_df = 
  read_csv("data/fivethirtyeight_datasets/snp.csv") %>%
  separate(
    date,
    into = c("month","day","year"),
    sep =  "/"
  ) %>%
  mutate(
    year = as.double(year),
    year = ifelse(year > 30, year + 1900, year + 2000),
    month = month.abb[as.integer(month)]
  ) %>%
  select(year, month, close)

unemp_df = 
  read_csv("data/fivethirtyeight_datasets/unemployment.csv") %>%
  pivot_longer(
    Jan:Dec,
    names_to = "Month",
    values_to = "Unemployment"
  ) %>%
  janitor::clean_names() %>%
  na.omit()

joined_df =
  full_join(pol_df, snp_df) %>%
  full_join(unemp_df) %>%
  mutate(date = lubridate::make_date(year,match(month,month.abb))) %>%
  select(year,month,date,everything())

joined_df
```

    ## # A tibble: 823 × 12
    ##     year month date       gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem
    ##    <dbl> <chr> <date>       <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
    ##  1  1947 Jan   1947-01-01      23      51     253      23      45     198
    ##  2  1947 Feb   1947-02-01      23      51     253      23      45     198
    ##  3  1947 Mar   1947-03-01      23      51     253      23      45     198
    ##  4  1947 Apr   1947-04-01      23      51     253      23      45     198
    ##  5  1947 May   1947-05-01      23      51     253      23      45     198
    ##  6  1947 Jun   1947-06-01      23      51     253      23      45     198
    ##  7  1947 Jul   1947-07-01      23      51     253      23      45     198
    ##  8  1947 Aug   1947-08-01      23      51     253      23      45     198
    ##  9  1947 Sep   1947-09-01      23      51     253      23      45     198
    ## 10  1947 Oct   1947-10-01      23      51     253      23      45     198
    ## # … with 813 more rows, and 3 more variables: president <chr>, close <dbl>,
    ## #   unemployment <dbl>

The `pol_df` contains information for the number of national politicians
by political party as well as the party of the president in different
months. The `snp_df` contains the Standard&Poor stock market index by
month, and the `unemployment_df` is the percentage of unemployment rate
in different months.

After cleaning and merging the three datasets, the `joined_df` contains
their information for 823 months, ranging from 1947-01-01 to 2015-07-01.
For each month, there are 12 columns having the date, political, stock
market and unemployment infomation with some missing values.
